# Generated by Django 3.0 on 2020-04-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='eagle1.jpg', upload_to='gallery'),
        ),
    ]
