# Generated by Django 3.0 on 2020-04-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='eagle-1.jpg', upload_to='gallery'),
        ),
    ]
